import { Dialog, DialogContent } from "@/components/ui/dialog";
import { CRQRecord } from "./data";
import { useState, useEffect } from "react";
import { cn } from "@/lib/utils";
import {
  FileText,
  UploadCloud,
  ThumbsUp,
  ThumbsDown,
  XCircle,
  CheckCircle2,
  MessageSquare,
  Paperclip,
} from "lucide-react";

const OUTCOMES = [
  { id: "PASS", label: "PASS (SUCCESS)", icon: ThumbsUp, color: "text-green-600", border: "border-green-300", bg: "bg-green-50" },
  { id: "FAILED", label: "FAILED", icon: ThumbsDown, color: "text-red-600", border: "border-red-300", bg: "bg-red-50" },
  { id: "CANCELED", label: "CANCELED", icon: XCircle, color: "text-slate-500", border: "border-slate-300", bg: "bg-slate-100" },
] as const;

export function MopUploadPanel({
  crqId,
  onCancel,
  onSubmit,
  prefilledFilename,
}: {
  crqId: string;
  onCancel?: () => void;
  onSubmit?: () => void;
  /** Filename auto-injected from the MOP tool (Infrasol / GRASP) */
  prefilledFilename?: string;
}) {
  const [pick, setPick] = useState<string | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [autoFilled, setAutoFilled] = useState(false);
  const [remark, setRemark] = useState("");
  const [rejectionReason, setRejectionReason] = useState("");
  const [rejectionOwner, setRejectionOwner] = useState("");
  const [successMsg, setSuccessMsg] = useState(false);

  // When a prefilled filename arrives (from Infrasol / GRASP), create a mock File object
  useEffect(() => {
    if (prefilledFilename && !autoFilled) {
      // Create a tiny dummy PDF blob so the rest of the form treats it as uploaded
      const blob = new Blob([`%PDF-1.4 auto-generated MOP for ${crqId}`], { type: "application/pdf" });
      const mockFile = new File([blob], prefilledFilename, { type: "application/pdf" });
      setFile(mockFile);
      setAutoFilled(true);
    }
  }, [prefilledFilename, autoFilled, crqId]);

  const canSubmit =
    pick &&
    (pick === "PASS" || (pick !== "PASS" && rejectionReason && rejectionOwner)) &&
    file;

  const handlePick = (id: string) => {
    setPick(id);
    if (id === "PASS") {
      setSuccessMsg(true);
      setTimeout(() => setSuccessMsg(false), 2000);
      setRejectionReason("");
      setRejectionOwner("");
    }
  };

  return (
    <div className="bg-white">
      <div className="sticky top-0 z-10 bg-white border-b border-slate-100 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="h-9 w-9 rounded-lg bg-rose-50 grid place-items-center text-rose-600">
            <FileText className="h-5 w-5" />
          </div>
          <div className="flex items-center gap-3">
            <span className="text-sm font-semibold text-slate-800">Upload and Finalize MOP</span>
            <span className="text-slate-300">|</span>
            <span className="text-xs text-slate-500">
              CRQ No: <span className="font-mono text-slate-700">{crqId}</span>
            </span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-0">
        {/* ── Upload zone ── */}
        <div className="col-span-12 md:col-span-6 border-r border-slate-100 p-5">
          {autoFilled && file ? (
            /* Auto-filled state */
            <div className="h-[360px] border-2 border-dashed border-green-300 rounded-xl bg-green-50/40 flex flex-col items-center justify-center gap-3 px-6">
              <div className="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
                <CheckCircle2 className="h-6 w-6 text-green-600" />
              </div>
              <div className="text-center">
                <p className="text-sm font-semibold text-green-800">MOP auto-attached</p>
                <p className="text-[11px] text-green-700 mt-0.5 font-mono font-medium">{file.name}</p>
                <p className="text-[10px] text-green-600 mt-1">Generated by MOP creation tool</p>
              </div>
              <div className="flex items-center gap-1.5 text-[10px] text-slate-500">
                <Paperclip className="h-3 w-3" />
                <span>or</span>
                <label className="cursor-pointer text-indigo-600 hover:underline font-medium">
                  replace with a different file
                  <input
                    type="file"
                    accept="application/pdf"
                    className="hidden"
                    onChange={(e) => {
                      setFile(e.target.files?.[0] ?? null);
                      setAutoFilled(false);
                    }}
                  />
                </label>
              </div>
            </div>
          ) : (
            /* Manual upload state */
            <label className="block h-[360px] border-2 border-dashed border-slate-300 rounded-xl bg-slate-50/40 grid place-items-center cursor-pointer hover:bg-slate-50 transition">
              <div className="text-center px-6">
                <UploadCloud className="h-10 w-10 text-slate-400 mx-auto mb-3" />
                <div className="text-sm font-medium text-slate-700">
                  {file ? file.name : "Click to upload or drag & drop"}
                </div>
                <div className="text-xs text-slate-400 mt-1">PDF only (Max 50MB)</div>
              </div>
              <input
                type="file"
                accept="application/pdf"
                className="hidden"
                onChange={(e) => setFile(e.target.files?.[0] ?? null)}
              />
            </label>
          )}
        </div>

        {/* ── Right: Outcome + remarks ── */}
        <div className="col-span-12 md:col-span-6 p-5 space-y-4">
          {successMsg && (
            <div className="flex items-center gap-2 rounded-lg bg-green-50 border border-green-200 px-4 py-3">
              <CheckCircle2 className="h-5 w-5 text-green-600 shrink-0" />
              <span className="text-sm font-semibold text-green-800">Status submitted successfully</span>
            </div>
          )}

          <div>
            <div className="text-sm font-semibold text-slate-800">MOP Creation Review</div>
            <div className="text-xs text-slate-500 mt-1">Select the final outcome of the MOP Creation.</div>
          </div>
          <div className="h-px bg-slate-100" />
          <div className="space-y-2.5">
            {OUTCOMES.map((o) => {
              const Icon = o.icon;
              const active = pick === o.id;
              return (
                <div key={o.id}>
                  <button
                    onClick={() => handlePick(o.id)}
                    className={cn(
                      "w-full flex items-center gap-3 px-4 py-3 rounded-xl border-2 transition-all duration-200",
                      active ? `${o.border} ${o.bg} shadow-sm` : "border-slate-200 hover:border-slate-300"
                    )}
                  >
                    <Icon className={cn("h-5 w-5", o.color)} />
                    <span className="text-sm font-semibold text-slate-700">{o.label}</span>
                  </button>

                  {active && (o.id === "FAILED" || o.id === "CANCELED") && (
                    <div className="mt-2 p-3 rounded-lg border border-amber-200 bg-amber-50 space-y-3">
                      <h4 className="font-semibold text-amber-900 text-xs">Rejection Details</h4>
                      <div>
                        <label className="text-xs font-semibold text-slate-700 mb-1 block">
                          Rejection Reason <span className="text-red-500">*</span>
                        </label>
                        <textarea
                          rows={2}
                          value={rejectionReason}
                          onChange={(e) => setRejectionReason(e.target.value)}
                          placeholder="Enter rejection reason..."
                          className="w-full border border-amber-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-300 resize-none"
                        />
                      </div>
                      <div>
                        <label className="text-xs font-semibold text-slate-700 mb-1 block">
                          Rejection Owner <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={rejectionOwner}
                          onChange={(e) => setRejectionOwner(e.target.value)}
                          placeholder="Enter owner name or ID..."
                          className="w-full border border-amber-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-300"
                        />
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          <div className="relative pt-3">
            <label className="absolute -top-1 left-2.5 px-1 bg-white text-[10px] uppercase tracking-wide font-medium text-slate-500">
              Remark (Optional)
            </label>
            <div className="flex gap-2 border border-slate-200 rounded-lg p-2 focus-within:ring-2 focus-within:ring-indigo-200 focus-within:border-indigo-400 transition">
              <MessageSquare className="h-4 w-4 text-slate-400 mt-1" />
              <textarea
                rows={4}
                value={remark}
                onChange={(e) => setRemark(e.target.value)}
                placeholder="Add any relevant notes…"
                className="flex-1 text-sm focus:outline-none resize-none bg-transparent"
              />
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-end gap-3 px-6 py-3 border-t border-slate-100 bg-slate-50/40">
        <button
          onClick={onCancel}
          className="text-xs font-medium text-slate-600 hover:text-slate-800 px-4 py-2 rounded-md"
        >
          CANCEL
        </button>
        <button
          onClick={() => canSubmit && onSubmit?.()}
          disabled={!canSubmit}
          className={cn(
            "inline-flex items-center gap-2 text-xs font-semibold px-4 py-2 rounded-md transition",
            canSubmit
              ? "bg-indigo-600 text-white hover:bg-indigo-700"
              : "bg-slate-200 text-slate-400 cursor-not-allowed"
          )}
        >
          <CheckCircle2 className="h-4 w-4" /> UPLOAD & SUBMIT STATUS
        </button>
      </div>
    </div>
  );
}

export function MopUploadModal({
  crq,
  onClose,
  prefilledFilename,
}: {
  crq: CRQRecord | null;
  onClose: () => void;
  prefilledFilename?: string;
}) {
  if (!crq) return null;
  return (
    <Dialog open={!!crq} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-5xl p-0 gap-0 overflow-hidden">
        <MopUploadPanel
          crqId={crq.id}
          onCancel={onClose}
          onSubmit={onClose}
          prefilledFilename={prefilledFilename}
        />
      </DialogContent>
    </Dialog>
  );
}